version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=real_estate_db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_PORT=3306
      - JWT_SECRET=your-very-secret-jwt-key-change-in-production-real-estate-pms-2024
      - JWT_EXPIRE=3600
      - JWT_REFRESH_EXPIRE=604800
      - APP_DEBUG=true
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - CLOUDINARY_CLOUD_NAME=your-cloud-name
      - CLOUDINARY_API_KEY=your-api-key
      - CLOUDINARY_API_SECRET=your-api-secret
    depends_on:
      - db
    volumes:
      - ./uploads:/var/www/html/uploads

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=real_estate_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
